APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:C2sz1FU3RwWQkL+ZqBu9k/fqmLI6UbEtA9hL125LwF4=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=sipta
DB_USERNAME=root
DB_PASSWORD=